dist: xenial
os: linux
language: node_js
node_js:
  - 12

services:
  - docker
  - postgresql

addons:
  postgresql: "13"
  apt:
    packages:
      - postgresql-13
      - postgresql-client-13

before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo systemctl restart postgresql@13-main
  - sleep 1

before_script:
  - . features/.env
  - export DB_PASSWORD='' DB_HOSTNAME='localhost' DB_PORT=$PGPORT
  - psql -c "CREATE DATABASE $DB_NAME;" -U postgres
  - docker pull trufflesuite/ganache-cli:latest
  - export NODE_URL='http://localhost:8545'
  - docker run --detach --publish 8545:8545 trufflesuite/ganache-cli:latest

script:
  - npm run test:coverage
  - codecov -f coverage/*.json

deploy:
  provider: script
  script: bash docker/heroku_push.sh
  cleanup: true
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH = master || $TRAVIS_BRANCH = develop

env:
  global:
    - PGPORT=5433
