version: '3'
services:
  app:
    image: node:12.19.0-alpine3.12
    ports:
      - "3000:${PORT}"
    working_dir: /app
    command: npm run devStart
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0-alpine
    hostname: "${DB_HOSTNAME}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - payments-service-postgres13-data:/var/lib/postgresql/data
    command: -p "${DB_PORT}"

volumes:
  payments-service-postgres13-data:
