version: '3.7'
services:
  payments-app:
    image: node:12.19.0-alpine3.12
    ports:
      - "4000:${PORT}"
    working_dir: /app
    command: npm run devStart
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - payments-net
      - bookbnb-net

  postgres:
    build: docker/postgres
    hostname: "${DB_HOSTNAME}"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - TEST_DB_NAME=${TEST_DB_NAME}
    volumes:
      - bookbnb-payments-postgres13-data:/var/lib/postgresql/data
    command: -p "${DB_PORT}"
    networks:
      - payments-net

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: -e 1000000 -s asecretseed
    networks:
      - payments-net

volumes:
  bookbnb-payments-postgres13-data:
  bookbnb-payments-pgAdmin-data:

networks:
  payments-net:
  bookbnb-net:
    name: bookbnb-net
