apiVersion: v1
kind: Service
metadata:
  name: bookbnb-payments-service
  labels:
    run: bookbnb-payments-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: payments-port
  selector:
    app: bookbnb-payments
